### PR TITLE
userscript version of the Chrome extension

### LINKED ISSUE #20: add an userscript version of the Chrome extension
just added this to the top of the script and it worked on Violentmonkey firefox

```
// ==UserScript==
// @name        Useful Forks
// @namespace   https://github.com/useful-forks
// @match       *://github.com/*/network/members
// @grant       none
// @version     1.5
// @icon        https://useful-forks.github.io/assets/useful-forks-logo.png
// @author      Useful Forks
// @description Displays GitHub forks ordered by stars, and with additional information and automatic filters.
// @require     https://code.jquery.com/jquery-3.5.1.min.js

// ==/UserScript==
// put the script down here !!
```

### PR DESCRIPTION
**Pull request by odnar-dev**
closes #20

### CODE REVIEW

**Comment by odnar-dev** [comment]
menu to make it easy to add GITHUB_ACCESS_TOKEN or change it

show error if GITHUB_ACCESS_TOKEN has not been set up

hover color is adapted to GitHub's Night-Mode. (need better colors)

**Comment by payne911** [comment]
That is looking like some really great work: I'll review the PR in the coming days. Thanks a lot for your contribution !

**Comment by payne911** [comment]
(Sorry, I thought changing the title would link the other issue, but I ended up having to edit your OP.)

**Comment by payne911** [comment]
> `document.addEventListener('pjax:end', init);`

Is that what fixes #9 ?

Also, does Violentmonkey requier the whole script to be within that `(function() { /* code */ })();` wrapper ?

**Comment by odnar-dev** [comment]
> `document.addEventListener('pjax:end', init);`
> Is that what fixes #9 ?

yes , github use for some pages Pjax to deliver a faster browsing experience without reloading the full page.
[check this](https://github.com/Mottie/GitHub-userscripts/wiki/How-to#main-content-pjax-containers)

> does Violentmonkey require the script to be within that (function() { /* code */ })(); wrapper ?

i don't think so , just a habit

**Comment by payne911** [comment]
Would you mind creating 2 extra PRs for the fixes of #4 and #9 ? I'd do it myself, but I'll respect your "ownership" of the solutions, in case you wanted to be labeled as a contributor. I'd merge both those PRs into the Chrome script.

For this current PR, I don't have a lot of time to test it just yet. I'll eventually try to simply add your `// ==UserScript==` right at the top of the Chrome script.

**Comment by payne911** [comment]
Alright, #25 was perfect, thanks for that!

I tried to incorporate your fix for #9 but couldn't get it to work properly. Have you tested if those cases work properly:
1. landing directly on the Forks page (test with: https://github.com/useful-forks/useful-forks.github.io/network/members)
2. refreshing the page when on the Forks page works (just press F5 when at the URL presented above)

**Comment by payne911** [comment]
Alright, now that I've incorporated both of your side-fixes into the main branch, it could be interesting to look into what this actually has to offer.

Have you tried incorporating your code directly into the Chrome plugin's script and seeing how well it works for people with and without `Violentmonkey` ?

**Comment by odnar-dev** [comment]
[Violentmonkey](https://violentmonkey.github.io/) is an userscript manager
this part of the script use a group of special [apis](https://violentmonkey.github.io/api/gm/) provided only by an userscript manager.
```js
// get token from local storage provided by the userscript manager.
let GITHUB_ACCESS_TOKEN = GM_getValue('GITHUB_ACCESS_TOKEN')
// add menu 
GM_registerMenuCommand("Set Github Access Token", setPersonalToken)
GM_registerMenuCommand("Generate New Access Token", newPersonalToken);
// store token in local storage provided by the userscript manager.
function setPersonalToken(){
    var mess = "Personal Access Token";
    var caseShow = GITHUB_ACCESS_TOKEN;
    var getpersonalToken = prompt(mess, caseShow);
    GITHUB_ACCESS_TOKEN = (getpersonalToken===null? GITHUB_ACCESS_TOKEN : getpersonalToken)
    GM_setValue("GITHUB_ACCESS_TOKEN", GITHUB_ACCESS_TOKEN)
}
// open url to generate a new personal token in new tab
function newPersonalToken(){
  let tabControl = GM_openInTab("https://github.com/settings/tokens/new?scopes=repo&description=UsefulFork")
  tabControl.onclose = () => setPersonalToken();
}
```
this should work in most other userscript managers (like Greasemonkey, Tampermonkey..)

**Review by HTML-CODDER — APPROVED** [review]
1.* please can I use this version

**Comment by payne911** [comment]
My main concern is the duplication of code. Is there a way to integrate it within the chrome script in a non-intrusive way?

**Comment by Metacinnabar** [comment]
Any update? This would be a great addition!

**Comment by payne911** [comment]
As mentioned, I'm kind of bothered by the duplication of code. See https://github.com/useful-forks/useful-forks.github.io/pull/21#issuecomment-849303400.

**Comment by odnar-dev** [comment]
> i'm kind of bothered by the duplication of code

what about creating a separate file that contain all shared functions and variables
then simply include it to chrome script and userscript

**Comment by payne911** [comment]
> what about creating a separate file that contain all shared functions and variables

Maybe that could work.

As a Java dev, what comes to mind is abstracting with an interface that has a few default methods for the shared ones, and then some different implementations for the Chrome and Monkey plugins.

**Comment by payne911** [comment]
The plugin has been heavily modified (see https://github.com/useful-forks/useful-forks.github.io/commit/63b9a3c49dd1bce9e1daf93dd4ea90bda002594e).

I'm closing the PR because it would basically need a rewrite anyways.

Note: the code duplication issue I had mentioned would not be there anymore, so there's a much higher likelihood that I would merge this kind of effort if the PR gets rewritten.

**Pull request closed without merging**
