### PR TITLE
Sort by number of commits ahead instead of stars

### PR DESCRIPTION
**Pull request by devnoname120**
Deployed at: https://devnoname120.github.io/useful-forks

### CODE REVIEW

**Comment by payne911** [comment]
I don't think I'd merge this given it's a rather arbitrary change.
I would rather love to see #48 appropriately addressed as it would allow the needed flexibility.

**Comment by devnoname120** [comment]
What do you mean with arbitrary? I consistently get more useful results with number of commits. Highly starred forks are routinely abandoned too and the successors can take years before reaching the same number of stars.

**Comment by payne911** [comment]
But the high amount of stars at least guarantee that the (potentially few) changes that were made were actually very much appreciated by the community.
Whereas I see tons of people forking repos, and doing a bunch of useless changes to `Readme.md` just to seemingly gather higher commit counts on their GitHub profile... probably in hope to boost their resume?

Anyhow, again: the best way forward is to implement a generic sorting functionality :)

**Comment by devnoname120** [comment]
Well to be honest I haven't seen this to be an issue within the context of this tool. Useless changes to `README.md` rarely make it to the top. You can have 10 useless commits, but rarely a hundred. On the other hand, the issue that this pull request resolves is something I stumble upon almost every time I perform a search.

Here is an example: https://github.com/dylanaraps/neofetch

While I agree that implementing a generic sorting functionality would be nice it's a lot more work. Also IMO it doesn't necessarily make reconsidering the choice of defaults outdated. As far as I'm concerned the change suggested in this pull request solves 99% of the problem for me. Not a hill I want to die on though, I will just maintain my fork if it's not merged.

**Pull request closed without merging**
