### PR TITLE
pjax listener 

### PR DESCRIPTION
**Pull request by odnar-dev**
closes : https://github.com/useful-forks/useful-forks.github.io/issues/9

### CODE REVIEW

**Comment by payne911** [comment]
Have you tested the 2 scenarios I mentioned there? https://github.com/useful-forks/useful-forks.github.io/pull/21#issuecomment-802530653

**Comment by odnar-dev** [comment]
> Have you tested the 2 scenarios I mentioned there? [#21 (comment)](https://github.com/useful-forks/useful-forks.github.io/pull/21#issuecomment-802530653)

yes

**Comment by payne911** [comment]
Interesting. I think what I had gotten wrong was the `manifest.json` config change from `"*://github.com/*/network/members"` to `"*://github.com/*/*"`.

Would you mind explaining why that is necessary ? I thought keeping the `matches` as restrictive as possible would be the best.

**Comment by odnar-dev** [comment]
when you go to [Dependencies](https://github.com/useful-forks/useful-forks.github.io/network/dependencies) then click on **Forks** it look like the whole page changed but what actually happened is that :
- Pjax fetched only partes of **Forks** page via AJAX and rendered it without reloading the page layout or any resources (js, css ...)
- then it updates the browser's current URL using `history.pushstat`

i added an event listeners that monitor pjax requests then call `init()` after it ended.
> `document.addEventListener('pjax:end', init); `

the `init()` function well check if current URL is `"*://github.com/*/network/members"` then add css and run initial_request()
> `if (pathComponents[4] == "members"){...`

**Comment by odnar-dev** [comment]
chrome extensions normally doesnt monitor `history.pushstat` so when you go to **Forks** from [Dependencies page](https://github.com/useful-forks/useful-forks.github.io/network/dependencies) your extension didn't get enabled cause chrome still think you are in the **Dependencies page**

**Comment by odnar-dev** [comment]
if you wanna keep the `matches` as restrictive as possible you need to add every page that link to **Forks page** and use pjax
```json
      "matches": [
        "*://github.com/*/*/community",
        "*://github.com/*/*/graphs/*",
        "*://github.com/*/*/network/*",
        "*://github.com/*/*/pulse"
      ],
```

**Comment by payne911** [comment]
Okay, you explained it really well, thank you!

**Pull request merged**
